version: '3.8'

services:
  mysql_ApiSinglePages:
    image: mysql:latest
    restart: always
    container_name: MySQL
    hostname: MySQL
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: RavenBox
      MYSQL_USER: RavenUser
      MYSQL_PASSWORD: 91553154
    volumes:
      - /var/lib/docker/volumes/mysqlRavenBox/_data:/var/lib/mysqlRavenBox

volumes:
  mysqlRavenBox: